export const citiesDictionary = {
    'воронеж': 'voronezh',
    'ярославль': 'yaroslavl',
    'белгород': 'belgorod',
    'санкт-петербург': 'saint-petersburg',
    'калининград': 'kaliningrad',
    'ростов-на-дону': 'rostov-on-don',
    'краснодар': 'krasnodar',
    'волгоград': 'volgograd',
    'казань': 'kazan',
    'самара': 'samara',
    'уфа': 'ufa',
    'оренбург': 'orenburg',
    'нижний новгород': 'novgorod',
    'екатеринбург': 'ekaterinburg',
    'челябинск': 'chelyabinsk',
    'пермь': 'permian',
    'сургут': 'surgut',
    'тюмень': 'tyumen',
    'ижевск': 'izhevsk',
    'новосибирск': 'novosibirsk',
    'омск': 'omsk',
    'томск': 'tomsk',
    'красноярск': 'krasnoyarsk',
    'иркутск': 'irkutsk',
    'хабаровск': 'khabarovsk',
    'владивосток': 'vladivostok'
  }